Vagrant.configure("2") do |config|
  config.env.enable
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider :google do |google, override|
    override.vm.box = "gce"

    google.name = ENV['TUSK_NAME']
    google.google_project_id = ENV['TUSK_PROJECT_ID']
    google.google_client_email = ENV['TUSK_CLIENT_EMAIL']
    google.google_key_location = "../../config/gcloud.p12"
    google.service_accounts = ["compute"]
    google.machine_type = "n1-highmem-16"
    google.zone = ENV.fetch('TUSK_ZONE', 'us-central1-b')

    override.ssh.username = "tim"
    #override.ssh.private_key_path = "~/.ssh/id_rsa"
    override.ssh.private_key_path = "~/.ssh/google_compute_engine"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./playbook.yml"
    config.ssh.forward_agent = true
    ansible.raw_ssh_args = ['-o UserKnownHostsFile=/dev/null -o ForwardAgent=yes']
  end
end
