Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb, override|
    override.vm.box = "chef/debian-7.4-i386"
    vb.customize [ "modifyvm", :id, "--hwvirtex", "off" ]
  end
  
  config.vm.provider :google do |google, override|
    override.vm.box = "gce"

    if ENV.fetch("GCLOUD_INSTANCE_NAME")
      google.image = ENV.fetch("GCLOUD_INSTANCE_NAME")
    end
    google.google_project_id = ENV.fetch("GCLOUD_PROJECT_ID")
    google.google_client_email = ENV.fetch("GCLOUD_CLIENT_EMAIL")
    google.google_key_location = File.realpath(File.dirname(__FILE__) + "/../../config/gcloud.p12")
    google.service_accounts = ENV.fetch("GCLOUD_PRIVILEGED") ? ["compute"] : nil
    google.machine_type = "n1-highmem-8"

    override.ssh.username = "tim"
    #override.ssh.private_key_path = "~/.ssh/id_rsa"
    override.ssh.private_key_path = "~/.ssh/google_compute_engine"
  end
end
